#!/usr/bin/env bash
# setup.sh
# Interactive setup script for BHC Scheduler -- Orchestrator (Linux)
# Generates orchestrator.conf and provisioning.json from user input.

set -e

OUT_DIR="${1:-config}"

# -- Colors ----------------------------------------
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
DGREEN='\033[0;32m'
GRAY='\033[0;37m'
NC='\033[0m' # No Color

echo ""
echo -e "${CYAN}  +==================================================+${NC}"
echo -e "${CYAN}  |        BHC Scheduler -- Interactive Setup        |${NC}"
echo -e "${CYAN}  +==================================================+${NC}"
echo ""

# -- Helper ----------------------------------------
ask() {
    local prompt="$1"
    local default="$2"
    local result
    if [ -n "$default" ]; then
        read -rp "  $prompt [$default]: " result
    else
        read -rp "  $prompt: " result
    fi
    if [ -z "$result" ]; then
        echo "$default"
    else
        echo "$result"
    fi
}

# -- Output directory ------------------------------
OUT_DIR=$(ask "Output directory for config files" "$OUT_DIR")
mkdir -p "$OUT_DIR"

# ==================================================
#  Part 1 -- orchestrator.conf
# ==================================================
echo ""
echo -e "${YELLOW}--- Orchestrator Configuration ---${NC}"
echo ""

# HTTP
listen_port=$(ask "HTTP listen port" "8080")

# Paths
echo ""
echo -e "${GRAY}Paths (relative to the executable, or absolute):${NC}"
work_dir=$(ask "Job work directory" "jobs")
db_path=$(ask "SQLite database path" "orchestrator.db")
provisioning_json=$(ask "Provisioning JSON path" "config/provisioning.json")
temp_dir=$(ask "Temp directory (empty = system default)" "")

# Logging
echo ""
log_level=$(ask "Log level (debug / info / warn / error)" "info")

# Scheduler
scheduler_poll_ms=$(ask "Scheduler poll interval (ms)" "500")
job_timeout_seconds=$(ask "Job timeout (seconds, 0 = none)" "3600")
cleanup_ttl_seconds=$(ask "Cleanup TTL (seconds, 0 = disabled)" "3600")

# Pre-job scripts
echo ""
echo -e "${GRAY}Pre-job scripts (executed before each job, leave empty to disable):${NC}"
pre_job_script_win=$(ask "Windows pre-job script" "")
pre_job_script_linux=$(ask "Linux pre-job script" "")

# SSH remote execution
echo ""
echo -e "${YELLOW}--- Remote SSH Execution ---${NC}"
echo -e "${GRAY}(Leave ssh_user empty for local-only mode)${NC}"
echo ""
ssh_user=$(ask "SSH user on remote job hosts" "")

ssh_key=""
ssh_remote_work_dir="/tmp/orch"

if [ -n "$ssh_user" ]; then
    default_key="$HOME/.ssh/orch_key"
    ssh_key=$(ask "SSH private key path (no passphrase)" "$default_key")
    ssh_remote_work_dir=$(ask "Remote work directory on job hosts" "/tmp/orch")
fi

# PID file
pid_file=$(ask "PID file path (daemon mode)" "/var/run/orchestrator.pid")

# -- Write orchestrator.conf -----------------------
conf_path="$OUT_DIR/orchestrator.conf"

cat > "$conf_path" <<EOF
# orchestrator.conf
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')
# All settings are optional -- built-in defaults are used for any missing key.
# Lines starting with '#' are comments.

# -- HTTP server -----------------------------------
listen_port         = $listen_port

# -- Pre-job scripts -------------------------------
# Executed at the start of each job. Leave empty to disable.
# Receives env vars: ORCH_JOB_ID, ORCH_INPUT_DIR, ORCH_OUTPUT_DIR,
#                    ORCH_MACHINE_IDS, ORCH_MACHINE_COUNT
pre_job_script_win   = $pre_job_script_win
pre_job_script_linux = $pre_job_script_linux

# -- Remote SSH execution -------------------------
# SSH user on remote machines. When set, jobs are dispatched via SSH.
# Leave blank for local-only mode.
ssh_user            = $ssh_user
#
# Path to the SSH private key (no passphrase). Absolute or relative to exe.
ssh_key             = $ssh_key
#
# Base working directory on remote machines (must be writable by ssh_user)
ssh_remote_work_dir = $ssh_remote_work_dir

# -- Paths -----------------------------------------
# All paths can be absolute or relative to the executable directory.
work_dir            = $work_dir
db_path             = $db_path
provisioning_json   = $provisioning_json

# Temporary directory for per-job known_hosts files and other temp data.
# Defaults to system temp (/tmp on Linux).
temp_dir            = $temp_dir

# PID file path (daemon mode).
pid_file            = $pid_file

# -- Logging ---------------------------------------
# Levels: debug | info | warn | error
log_level           = $log_level

# -- Scheduler -------------------------------------
# How often the scheduler checks for runnable jobs (milliseconds)
scheduler_poll_ms   = $scheduler_poll_ms

# -- Job timeout -----------------------------------
# Maximum seconds a job can be in STARTING or RUNNING before the scheduler
# marks it FAILED and releases its resources. 0 = no global timeout.
job_timeout_seconds = $job_timeout_seconds

# -- Cleanup ---------------------------------------
# Seconds after a job reaches a terminal state before its
# work directory (input/ + output/) is deleted.
# Set to 0 to disable automatic cleanup.
cleanup_ttl_seconds = $cleanup_ttl_seconds
EOF

echo ""
echo -e "${GREEN}  => $conf_path written.${NC}"

# ==================================================
#  Part 2 -- provisioning.json (job hosts)
# ==================================================
echo ""
echo -e "${YELLOW}--- Machine Provisioning (Job Hosts) ---${NC}"
echo -e "${GRAY}Add machines one by one. Press Enter with an empty ID to finish.${NC}"
echo ""

# Collect machines into parallel arrays
m_ids=()
m_hostnames=()
m_ips=()
m_enabled=()
m_cores=()
m_gpu=()
m_ram=()
m_disk=()

while true; do
    id=$(ask "Machine ID (e.g. srv-01, leave empty to finish)" "")
    [ -z "$id" ] && break

    hostname=$(ask "  Hostname" "$id")
    ip=$(ask "  IP address" "")
    enabled=$(ask "  Enabled (true/false)" "true")
    cores=$(ask "  CPU cores" "4")
    gpu_count=$(ask "  GPU count" "0")
    ram_mb=$(ask "  RAM (MB)" "8192")
    disk_mb=$(ask "  Disk (MB)" "102400")

    m_ids+=("$id")
    m_hostnames+=("$hostname")
    m_ips+=("$ip")
    m_enabled+=("$enabled")
    m_cores+=("$cores")
    m_gpu+=("$gpu_count")
    m_ram+=("$ram_mb")
    m_disk+=("$disk_mb")

    echo -e "${DGREEN}    + $id added.${NC}"
    echo ""
done

# Ask about pools
echo ""
echo -e "${GRAY}Add machine pools (range-based). Press Enter with empty prefix to skip.${NC}"
echo ""

p_prefixes=()
p_hostname_fmts=()
p_ip_fmts=()
p_range_starts=()
p_range_ends=()
p_enabled=()
p_cores=()
p_gpu=()
p_ram=()
p_disk=()

while true; do
    prefix=$(ask "Pool ID prefix (e.g. node-, leave empty to finish)" "")
    [ -z "$prefix" ] && break

    hostname_fmt=$(ask "  Hostname format (e.g. node-%03d.local)" "${prefix}%03d")
    ip_fmt=$(ask "  IP format (e.g. 10.0.1.%d)" "")
    range_start=$(ask "  Range start" "1")
    range_end=$(ask "  Range end" "10")
    pe=$(ask "  Enabled (true/false)" "true")
    pc=$(ask "  Cores per machine" "4")
    pg=$(ask "  GPUs per machine" "0")
    pr=$(ask "  RAM per machine (MB)" "8192")
    pd=$(ask "  Disk per machine (MB)" "102400")

    p_prefixes+=("$prefix")
    p_hostname_fmts+=("$hostname_fmt")
    p_ip_fmts+=("$ip_fmt")
    p_range_starts+=("$range_start")
    p_range_ends+=("$range_end")
    p_enabled+=("$pe")
    p_cores+=("$pc")
    p_gpu+=("$pg")
    p_ram+=("$pr")
    p_disk+=("$pd")

    echo -e "${DGREEN}    + pool ${prefix}[$range_start..$range_end] added.${NC}"
    echo ""
done

# -- Build JSON ------------------------------------
prov_path="$OUT_DIR/provisioning.json"

# Escape a string for JSON (backslashes and double quotes)
json_escape() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

{
    echo "{"
    echo '  "machines": ['

    count=${#m_ids[@]}
    for (( i=0; i<count; i++ )); do
        comma=","
        [ $((i + 1)) -eq "$count" ] && comma=""
        echo "    {"
        echo "      \"id\":        \"$(json_escape "${m_ids[$i]}")\","
        echo "      \"hostname\":  \"$(json_escape "${m_hostnames[$i]}")\","
        echo "      \"ip\":        \"$(json_escape "${m_ips[$i]}")\","
        echo "      \"enabled\":   ${m_enabled[$i]},"
        echo "      \"cores\":     ${m_cores[$i]},"
        echo "      \"gpu_count\": ${m_gpu[$i]},"
        echo "      \"ram_mb\":    ${m_ram[$i]},"
        echo "      \"disk_mb\":   ${m_disk[$i]}"
        echo "    }$comma"
    done

    echo "  ],"
    echo '  "pools": ['

    count=${#p_prefixes[@]}
    for (( i=0; i<count; i++ )); do
        comma=","
        [ $((i + 1)) -eq "$count" ] && comma=""
        echo "    {"
        echo "      \"id_prefix\":       \"$(json_escape "${p_prefixes[$i]}")\","
        echo "      \"hostname_format\": \"$(json_escape "${p_hostname_fmts[$i]}")\","
        echo "      \"ip_format\":       \"$(json_escape "${p_ip_fmts[$i]}")\","
        echo "      \"range_start\":     ${p_range_starts[$i]},"
        echo "      \"range_end\":       ${p_range_ends[$i]},"
        echo "      \"enabled\":         ${p_enabled[$i]},"
        echo "      \"cores\":           ${p_cores[$i]},"
        echo "      \"gpu_count\":       ${p_gpu[$i]},"
        echo "      \"ram_mb\":          ${p_ram[$i]},"
        echo "      \"disk_mb\":         ${p_disk[$i]}"
        echo "    }$comma"
    done

    echo "  ]"
    echo "}"
} > "$prov_path"

# Count total machines
total_machines=${#m_ids[@]}
for (( i=0; i<${#p_prefixes[@]}; i++ )); do
    pool_count=$(( p_range_ends[i] - p_range_starts[i] + 1 ))
    total_machines=$(( total_machines + pool_count ))
done

echo ""
echo -e "${GREEN}  => $prov_path written (${#m_ids[@]} machine(s), ${#p_prefixes[@]} pool(s), $total_machines total).${NC}"

# ==================================================
#  Summary
# ==================================================
echo ""
echo -e "${YELLOW}--- Setup Complete ---${NC}"
echo ""
echo "  Config:       $conf_path"
echo "  Provisioning: $prov_path"
echo ""
echo -e "${GRAY}Next steps:${NC}"
echo "  1. Build:    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build"
echo "  2. API key:  ./build/bin/orchestrator keygen --label my-app"
echo "  3. Run:      ./build/bin/orchestrator"
echo "  4. Daemon:   ./build/bin/orchestrator --daemon"
echo ""
