# setup.ps1
# Interactive setup script for BHC Scheduler -- Orchestrator
# Generates orchestrator.conf and provisioning.json from user input.

param(
    [string]$OutDir = ""
)

$banner = @"

  +==================================================+
  |        BHC Scheduler -- Interactive Setup        |
  +==================================================+

"@
Write-Host $banner -ForegroundColor Cyan

# -- Helper ----------------------------------------
function Ask([string]$Prompt, [string]$Default) {
    $display = if ($Default) { "$Prompt [$Default]" } else { $Prompt }
    $val = Read-Host $display
    if ([string]::IsNullOrWhiteSpace($val)) { return $Default }
    return $val.Trim()
}

# -- Output directory ------------------------------
if (-not $OutDir) {
    $OutDir = Ask "Output directory for config files" "config"
}
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

# ==================================================
#  Part 1 -- orchestrator.conf
# ==================================================
Write-Host ""
Write-Host "--- Orchestrator Configuration ---" -ForegroundColor Yellow
Write-Host ""

# HTTP
$listen_port = Ask "HTTP listen port" "8080"

# Paths
Write-Host ""
Write-Host "Paths (relative to the executable, or absolute):" -ForegroundColor Gray
$work_dir          = Ask "  Job work directory" "jobs"
$db_path           = Ask "  SQLite database path" "orchestrator.db"
$provisioning_json = Ask "  Provisioning JSON path" "config/provisioning.json"
$temp_dir          = Ask "  Temp directory (empty = system default)" ""

# Logging
Write-Host ""
$log_level = Ask "Log level (debug / info / warn / error)" "info"

# Scheduler
$scheduler_poll_ms   = Ask "Scheduler poll interval (ms)" "500"
$job_timeout_seconds = Ask "Job timeout (seconds, 0 = none)" "3600"
$cleanup_ttl_seconds = Ask "Cleanup TTL (seconds, 0 = disabled)" "3600"

# Pre-job scripts
Write-Host ""
Write-Host "Pre-job scripts (executed before each job, leave empty to disable):" -ForegroundColor Gray
$pre_job_script_win   = Ask "  Windows pre-job script" "config\pre_job_script_win.bat"
$pre_job_script_linux = Ask "  Linux pre-job script" ""

# SSH remote execution
Write-Host ""
Write-Host "--- Remote SSH Execution ---" -ForegroundColor Yellow
Write-Host "(Leave ssh_user empty for local-only mode)" -ForegroundColor Gray
Write-Host ""
$ssh_user = Ask "SSH user on remote job hosts" ""

$ssh_key             = ""
$ssh_remote_work_dir = "/tmp/orch"

if ($ssh_user) {
    $defaultKey = "$env:USERPROFILE\.ssh\orch_key"
    $ssh_key             = Ask "SSH private key path (no passphrase)" $defaultKey
    $ssh_remote_work_dir = Ask "Remote work directory on job hosts" "/tmp/orch"
}

# PID file (Linux only)
$pid_file = Ask "PID file path (Linux daemon only)" "/var/run/orchestrator.pid"

# -- Write orchestrator.conf -----------------------
$confPath = Join-Path $OutDir "orchestrator.conf"

$confContent = @"
# orchestrator.conf
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# All settings are optional -- built-in defaults are used for any missing key.
# Lines starting with '#' are comments.

# -- HTTP server -----------------------------------
listen_port         = $listen_port

# -- Pre-job scripts -------------------------------
# Executed at the start of each job. Leave empty to disable.
# Receives env vars: ORCH_JOB_ID, ORCH_INPUT_DIR, ORCH_OUTPUT_DIR,
#                    ORCH_MACHINE_IDS, ORCH_MACHINE_COUNT
pre_job_script_win   = $pre_job_script_win
pre_job_script_linux = $pre_job_script_linux

# -- Remote SSH execution -------------------------
# SSH user on remote machines. When set, jobs are dispatched via SSH.
# Leave blank for local-only mode.
ssh_user            = $ssh_user
#
# Path to the SSH private key (no passphrase). Absolute or relative to exe.
ssh_key             = $ssh_key
#
# Base working directory on remote machines (must be writable by ssh_user)
ssh_remote_work_dir = $ssh_remote_work_dir

# -- Paths -----------------------------------------
# All paths can be absolute or relative to the executable directory.
work_dir            = $work_dir
db_path             = $db_path
provisioning_json   = $provisioning_json

# Temporary directory for per-job known_hosts files and other temp data.
# Defaults to system temp (TEMP on Windows, /tmp on Linux).
temp_dir            = $temp_dir

# PID file path (Linux daemon mode only).
pid_file            = $pid_file

# -- Logging ---------------------------------------
# Levels: debug | info | warn | error
log_level           = $log_level

# -- Scheduler -------------------------------------
# How often the scheduler checks for runnable jobs (milliseconds)
scheduler_poll_ms   = $scheduler_poll_ms

# -- Job timeout -----------------------------------
# Maximum seconds a job can be in STARTING or RUNNING before the scheduler
# marks it FAILED and releases its resources. 0 = no global timeout.
job_timeout_seconds = $job_timeout_seconds

# -- Cleanup ---------------------------------------
# Seconds after a job reaches a terminal state before its
# work directory (input/ + output/) is deleted.
# Set to 0 to disable automatic cleanup.
cleanup_ttl_seconds = $cleanup_ttl_seconds
"@

Set-Content -Path $confPath -Value $confContent -Encoding UTF8
Write-Host ""
Write-Host "  => $confPath written." -ForegroundColor Green

# -- Part 2 -- provisioning.json (job hosts) --------------
Write-Host ""
Write-Host "--- Machine Provisioning (Job Hosts) ---" -ForegroundColor Yellow
Write-Host "Add machines one by one. Press Enter with an empty ID to finish." -ForegroundColor Gray
Write-Host ""

$machines = @()

while ($true) {
    $id = Ask "  Machine ID (e.g. srv-01, leave empty to finish)" ""
    if ([string]::IsNullOrWhiteSpace($id)) { break }

    $hostname  = Ask "    Hostname" $id
    $ip        = Ask "    IP address" ""
    $enabled   = Ask "    Enabled (true/false)" "true"
    $cores     = Ask "    CPU cores" "4"
    $gpu_count = Ask "    GPU count" "0"
    $ram_mb    = Ask "    RAM (MB)" "8192"
    $disk_mb   = Ask "    Disk (MB)" "102400"

    $machines += [PSCustomObject]@{
        id        = $id
        hostname  = $hostname
        ip        = $ip
        enabled   = ($enabled -eq "true")
        cores     = [int]$cores
        gpu_count = [int]$gpu_count
        ram_mb    = [int]$ram_mb
        disk_mb   = [int]$disk_mb
    }

    Write-Host "    + $id added." -ForegroundColor DarkGreen
    Write-Host ""
}

# Ask about pools
Write-Host ""
Write-Host "Add machine pools (range-based). Press Enter with empty prefix to skip." -ForegroundColor Gray
Write-Host ""

$pools = @()

while ($true) {
    $prefix = Ask "  Pool ID prefix (e.g. node-, leave empty to finish)" ""
    if ([string]::IsNullOrWhiteSpace($prefix)) { break }

    $hostname_fmt = Ask "    Hostname format (e.g. node-%03d.local)" "${prefix}%03d"
    $ip_fmt       = Ask "    IP format (e.g. 10.0.1.%d)" ""
    $range_start  = Ask "    Range start" "1"
    $range_end    = Ask "    Range end" "10"
    $p_enabled    = Ask "    Enabled (true/false)" "true"
    $p_cores      = Ask "    Cores per machine" "4"
    $p_gpu        = Ask "    GPUs per machine" "0"
    $p_ram        = Ask "    RAM per machine (MB)" "8192"
    $p_disk       = Ask "    Disk per machine (MB)" "102400"

    $pools += [PSCustomObject]@{
        id_prefix       = $prefix
        hostname_format = $hostname_fmt
        ip_format       = $ip_fmt
        range_start     = [int]$range_start
        range_end       = [int]$range_end
        enabled         = ($p_enabled -eq "true")
        cores           = [int]$p_cores
        gpu_count       = [int]$p_gpu
        ram_mb          = [int]$p_ram
        disk_mb         = [int]$p_disk
    }

    Write-Host "    + pool ${prefix}[$range_start..$range_end] added." -ForegroundColor DarkGreen
    Write-Host ""
}

# -- Build JSON manually for clean formatting -----
function Escape-Json([string]$s) { return $s.Replace('\', '\\').Replace('"', '\"') }

$jsonLines = @()
$jsonLines += "{"
$jsonLines += '  "machines": ['

for ($i = 0; $i -lt $machines.Count; $i++) {
    $m = $machines[$i]
    $comma = if ($i -lt $machines.Count - 1) { "," } else { "" }
    $en = if ($m.enabled) { "true" } else { "false" }
    $jsonLines += "    {"
    $jsonLines += "      `"id`":        `"$(Escape-Json $m.id)`","
    $jsonLines += "      `"hostname`":  `"$(Escape-Json $m.hostname)`","
    $jsonLines += "      `"ip`":        `"$(Escape-Json $m.ip)`","
    $jsonLines += "      `"enabled`":   $en,"
    $jsonLines += "      `"cores`":     $($m.cores),"
    $jsonLines += "      `"gpu_count`": $($m.gpu_count),"
    $jsonLines += "      `"ram_mb`":    $($m.ram_mb),"
    $jsonLines += "      `"disk_mb`":   $($m.disk_mb)"
    $jsonLines += "    }$comma"
}

$jsonLines += "  ],"
$jsonLines += '  "pools": ['

for ($i = 0; $i -lt $pools.Count; $i++) {
    $p = $pools[$i]
    $comma = if ($i -lt $pools.Count - 1) { "," } else { "" }
    $en = if ($p.enabled) { "true" } else { "false" }
    $jsonLines += "    {"
    $jsonLines += "      `"id_prefix`":       `"$(Escape-Json $p.id_prefix)`","
    $jsonLines += "      `"hostname_format`": `"$(Escape-Json $p.hostname_format)`","
    $jsonLines += "      `"ip_format`":       `"$(Escape-Json $p.ip_format)`","
    $jsonLines += "      `"range_start`":     $($p.range_start),"
    $jsonLines += "      `"range_end`":       $($p.range_end),"
    $jsonLines += "      `"enabled`":         $en,"
    $jsonLines += "      `"cores`":           $($p.cores),"
    $jsonLines += "      `"gpu_count`":       $($p.gpu_count),"
    $jsonLines += "      `"ram_mb`":          $($p.ram_mb),"
    $jsonLines += "      `"disk_mb`":         $($p.disk_mb)"
    $jsonLines += "    }$comma"
}

$jsonLines += "  ]"
$jsonLines += "}"

$provPath = Join-Path $OutDir "provisioning.json"
Set-Content -Path $provPath -Value ($jsonLines -join "`n") -Encoding UTF8

$totalMachines = $machines.Count
foreach ($p in $pools) { $totalMachines += ($p.range_end - $p.range_start + 1) }

Write-Host ""
Write-Host "  => $provPath written ($($machines.Count) machine(s), $($pools.Count) pool(s), $totalMachines total)." -ForegroundColor Green

# ==================================================
#  Summary
# ==================================================
Write-Host ""
Write-Host "--- Setup Complete ---" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Config:       $confPath"
Write-Host "  Provisioning: $provPath"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Gray
Write-Host "  1. Build:    cmake -S . -B build; cmake --build build --config Release"
Write-Host "  2. API key:  .\build\bin\Release\orchestrator.exe keygen --label my-app"
Write-Host "  3. Run:      .\build\bin\Release\orchestrator.exe"
Write-Host ""
